Spinner implementation underway
Current error: FATAL EXCEPTION: main
Process: com.abdullahalshehabi.whatsfordinner, PID: 13113
java.lang.IllegalStateException: ArrayAdapter requires the resource ID
to be a TextView